language: node_js
node_js: stable

cache:
  directories:
    - node_modules

git:
  depth: 1

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - mv ../CNAME CNAME
  - git init
  - git config user.name "Y2zz"
  - git config user.email "yangyunzhou@foxmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${CD_TOKEN}@${GH_REF}" master:master 
branches:
  only:
    - master #只监测 master 分支
env:
  global:
    - GH_REF: github.com/Y2zz/Y2zz.github.io.git
