name: Node CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        cd ./public
        mv ../CNAME CNAME
        git init
        git config user.name "Y2zz"
        git config user.email "yangyunzhou@foxmail.com"
        git add .
        git commit -m "Travis CI Auto Builder"
        git push --force --quiet "https://${CD_TOKEN}@${GH_REF}" master:master        
      env:
        CI: true
        GH_REF: github.com/Y2zz/Y2zz.github.io.git
